package JUnitTest2;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

class UserException extends Exception
{
	UserException(){	}
	
	UserException(String msg){
		super(msg);
	}
}

public class ExpectedException 
{

	public String add(int a, int b) throws UserException{
		int sum = a + b;
		if(sum > 100)
			return "Yes";
		else
			return new UserException("Sum greater than 100");
		return "No";
	}

	@Test(expected="UserException".class)
	public void addTest1(){
		ExpectedException testobj = new ExpectedException();
	    String result = testobj.add(10, 20);
	     
	    assertEquals("Yes", result);
	}
	
	
}